### ISSUE TITLE
PDFDocument is passed by reference across thread boundaries but is not threadsafe: Qiqqa crashes 💥

### ISSUE THREAD

**Issue by GerHobbelt** [jimmejardine/qiqqa-open-source#101]
💥 

Another instance of PDFDocument causing trouble due to missing protection for cross-thread-boundary travels, where a *reader* thread will still expect *constant* (= *unmodified*) Dictionary, List, whathaveyou type(s).

Extract for the exception at hand, this time in DeepClone()'s internals: Serialize there discovering an edit by another thread at the same time --> 💣 💥 ::

```
System.ArgumentException
  HResult=0x80070057
  Message=Destination array is not long enough to copy all the items in the collection. Check array index and length.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.CopyTo(KeyValuePair`2[] array, Int32 index)
   at System.Collections.Generic.Dictionary`2.GetObjectData(SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Utilities.Cloning.DeepObjectCloner.DeepClone[T](T object_to_clone) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\Utilities\Cloning\DeepObjectCloner.cs:line 16
   at Utilities.Misc.DictionaryBasedObject.Clone() in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\Utilities\Misc\DictionaryBasedObject.cs:line 172
   at Qiqqa.Documents.PDF.PDFDocument.QueueToStorage() in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\Qiqqa\Documents\PDF\PDFDocument.cs:line 877
   at Qiqqa.Documents.PDF.PDFDocument.bindable_PropertyChanged(Object sender, PropertyChangedEventArgs e) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\Qiqqa\Documents\PDF\PDFDocument.cs:line 1002

Dictionary:
keys
    [0] "FileType"  string
    [1] "Fingerprint" string
    [2] "DateAddedToDatabase" string
    [3] "DateLastModified"  string
    [4] "DownloadLocation"  string
    [5] "BibTex"  string
    [6] "Comments"  string
    [7] "Tags"  string
    [8] "DateLastRead"  string
    [9] "AutoSuggested_PDFMetadata" string
    [10]  "AuthorsSuggested"  string
    [11]  "YearSuggested" string
    [12]  "AutoSuggested_OCRFrontPage"  string
    [13]  "TitleSuggested"  string
    [14]  "AutoSuggested_BibTeXSearch"  string

values
    [0] "pdf" object {string}
    [1] "1CC8863D52A759FF98D5622178BEBC088CFEBF"  object {string}
    [2] "20191009002444426" object {string}
    [3] "20191009002444426" object {string}
    [4] "W:\\Sopkonijn\\!QIQQA-pdf-watch-dir\\!1\\!from-old-drive\\Guest\\documents\\1\\1CC8863D52A759FF98D5622178BEBC088CFEBF.pdf" object {string}
    [5] null  object
    [6] null  object
    [7] ""  object {string}
    [8] null  object
    [9] true  object {bool}
    [10]  "GruhlA"  object {string}
    [11]  "2012"  object {string}
    [12]  true  object {bool}
    [13]  "A Novel Error-Tolerant Anonymous Linking Code" object {string}
    [14]  true  object {bool}
```

## Preliminary Analysis

Same root cause as #96: PDFDocument (and probably the other serialized objects in Qiqqa code) is not protected against simultaneous access by multiple threads. (As described above, even a *read* operation, i.e. a list/table *iteration*, is already very dangerous in C#.

**Comment by GerHobbelt** [comment]
Forgot to add: https://stackoverflow.com/questions/43041839/destination-array-is-not-long-enough-to-copy-all-the-items-in-the-collection-ch?rq=1#answer-43123224 is about this type of problem.

**Comment by GerHobbelt** [comment]
Considered a dupe of #96 as far as root cause is concerned. Further work will reference that one.
