### ISSUE TITLE
✅SyncFusion 14 locks up (hangs) when reading some PDF files

### ISSUE THREAD

**Issue by GerHobbelt** [jimmejardine/qiqqa-open-source#11]

**Comment by GerHobbelt** [comment]
(Part of?) the solution was to upgrade the files in `./libs/` to Syncfusion 17 files.

## Qiqqa Logging for SF 17 (SF 14 **hangs inside that SF.Pdf API call!)

>
> 20190801.233804 WARN  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] Problem in PDFMetadataInferenceFromPDFMetadata.InferFromPDFMetadata while processing document 824EFA4775A1EC0C518DCD5EA89274ABBF594


>
> Syncfusion.Pdf.PdfException: Cannot load document, the document structure has been corrupted.
>
>    at Syncfusion.Pdf.Parsing.PdfLoadedDocument.LoadDocument(Stream file)
>
>    at Syncfusion.Pdf.Parsing.PdfLoadedDocument..ctor(Stream file)
>
>    at Syncfusion.Pdf.Parsing.PdfLoadedDocument..ctor(String filename)
>
>    at Utilities.PDF.AugmentedPdfLoadedDocument..ctor(String filename)
>
>    at Qiqqa.Documents.PDF.MetadataSuggestions.PDFMetadataInferenceFromPDFMetadata.InferFromPDFMetadata(PDFDocument pdf_document)
>
>    at Qiqqa.DocumentLibrary.MetadataExtractionDaemonStuff.MetadataExtractionDaemon.DoMaintenance(Library library, Daemon daemon)
>

**Comment by GerHobbelt** [comment]
Adobe Acrobat DC says this about the offending PDF:

![2019-08-02A](https://user-images.githubusercontent.com/402462/62365291-04790180-b524-11e9-88ef-1711c39ee485.png)

**Comment by GerHobbelt** [comment]
PDF itself is 28MB and too large to upload to Github.

**Comment by GerHobbelt** [comment]
Done as per #33.

**Comment by GerHobbelt** [comment]
> Closing <sup>and decluttering the issue list so it stays workable for me</sup>: fixed in https://github.com/GerHobbelt/qiqqa-open-source mainline=master branch, pending #15 / any maintainer rights/actions.
