### ISSUE TITLE
Qiqqa throws exception (but does NOT crash) while saving text from a OCRed large pdf (721 pages)

### ISSUE THREAD

**Issue by GerHobbelt** [jimmejardine/qiqqa-open-source#172]
@raindropsfromsky commented 3 hours ago • (was filed as https://github.com/GerHobbelt/qiqqa-open-source/issues/11)

I tried to save the text from the OCRed version of a 721-page pdf file.
An exception box popped up.
Qiqqa does not crash, but it becomes inaccessible till I close the Exception box.

The first time I closed the box, and lost it 
(God only knows what happened to the crash information).

The second time I copied the information from the box, as follows:
(The box has four compartments, and I copied the content of all compartments here.)

```
**Exception has been thrown by the target of an invocation.**
----------------------------------------------------------------
20200324095913:System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Concat(String str0, String str1, String str2)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.get_StackTrace()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Utilities.Misc.ExceptionHelpers.<WriteExceptionDetails>g__append|0_0(String prop, Func`2 fmt, <>c__DisplayClass0_0& )
   at Utilities.Misc.ExceptionHelpers.WriteExceptionDetails(StringBuilder builderToFill, Exception exception, Int32 level)
   at Utilities.Misc.ExceptionHelpers.ToStringAllExceptionDetails(Exception exception)
   at Utilities.Logging.Error(Exception ex, String msg, Object[] args)
   at Qiqqa.Documents.PDF.PDFControls.PDFExporting.ExportToWord.DoExport(PDFDocument pdf_document)
   at Qiqqa.Documents.PDF.PDFControls.PDFExporting.ExportToWord.ExportToTextAndLaunch(PDFDocument pdf_document)
   at Qiqqa.Documents.PDF.PDFControls.PDFReadingControl.ButtonExportToText_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

--------------------------------------------

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Concat(String str0, String str1, String str2)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.get_StackTrace()

--------------------------------------------
HResult: 0x80004003
Source: PresentationFramework
StackTrace:    at System.Windows.Documents.SplayTreeNode.GetSiblingAtOffset(Int32 offset, Int32& nodeOffset)
   at System.Windows.Documents.TextTreeText.FindBlock(TextTreeRootTextBlock rootTextBlock, Int32 offset, Int32& localOffset)
   at System.Windows.Documents.TextTreeText.InsertText(TextTreeRootTextBlock rootTextBlock, Int32 offset, Object text)
   at System.Windows.Documents.TextContainer.InsertElementInternal(TextPointer startPosition, TextPointer endPosition, TextElement element)
   at System.Windows.Documents.TextElement.RepositionWithContent(TextPointer textPosition)
   at System.Windows.Documents.TextElementCollection`1.Add(TextElementType item)
   at Qiqqa.Documents.PDF.PDFControls.PDFExporting.ExportToWord.DoExport(PDFDocument pdf_document)
TargetSite: System.Windows.Documents.SplayTreeNode GetSiblingAtOffset(Int32, Int32 ByRef)

20200324.095911 [Q] DEBUG [Main] [491.338M] ExportToWord:Exporting page 378 (378/721: 52.4 %)
20200324.095911 [Q] INFO  [Main] [491.346M] Exporting page 378/721
20200324.095911 [Q] ERROR [Main] [491.370M] There was a problem exporting page 378

System.NullReferenceException
Message: Object reference not set to an instance of an object.
HResult: 0x80004003
Source: PresentationFramework
StackTrace:    at System.Windows.Documents.SplayTreeNode.GetSiblingAtOffset(Int32 offset, Int32& nodeOffset)
   at System.Windows.Documents.TextTreeText.FindBlock(TextTreeRootTextBlock rootTextBlock, Int32 offset, Int32& localOffset)
   at System.Windows.Documents.TextTreeText.InsertText(TextTreeRootTextBlock rootTextBlock, Int32 offset, Object text)
   at System.Windows.Documents.TextContainer.InsertElementInternal(TextPointer startPosition, TextPointer endPosition, TextElement element)
   at System.Windows.Documents.TextElement.RepositionWithContent(TextPointer textPosition)
   at System.Windows.Documents.TextElementCollection`1.Add(TextElementType item)
   at Qiqqa.Documents.PDF.PDFControls.PDFExporting.ExportToWord.DoExport(PDFDocument pdf_document)
TargetSite: System.Windows.Documents.SplayTreeNode GetSiblingAtOffset(Int32, Int32 ByRef)

20200324.095911 [Q] DEBUG [Main] [491.387M] ExportToWord:Exporting page 379 (379/721: 52.6 %)
20200324.095911 [Q] INFO  [Main] [491.395M] Exporting page 379/721
20200324.095911 [Q] ERROR [Main] [491.014M] RemarkOnException.....

System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
HResult: 0x80131604
Source: mscorlib
StackTrace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Utilities.Misc.ExceptionHelpers.<WriteExceptionDetails>g__append|0_0(String prop, Func`2 fmt, <>c__DisplayClass0_0& )
   at Utilities.Misc.ExceptionHelpers.WriteExceptionDetails(StringBuilder builderToFill, Exception exception, Int32 level)
   at Utilities.Misc.ExceptionHelpers.ToStringAllExceptionDetails(Exception exception)
   at Utilities.Logging.Error(Exception ex, String msg, Object[] args)
   at Qiqqa.Documents.PDF.PDFControls.PDFExporting.ExportToWord.DoExport(PDFDocument pdf_document)
   at Qiqqa.Documents.PDF.PDFControls.PDFExporting.ExportToWord.ExportToTextAndLaunch(PDFDocument pdf_document)
   at Qiqqa.Documents.PDF.PDFControls.PDFReadingControl.ButtonExportToText_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
 System.Object = 
 === INNER EXCEPTION ===
 System.OutOfMemoryException
 Message: Exception of type 'System.OutOfMemoryException' was thrown.
 HResult: 0x8007000E
 Source: mscorlib
 StackTrace:    at System.String.Concat(String str0, String str1, String str2)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.get_StackTrace()
 TargetSite: System.String Concat(System.String, System.String, System.String)

20200324.095911 [Q] ERROR [Main] [491.185M] RemarkOnException_GUI_THREAD...

System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
HResult: 0x80131604
Source: mscorlib
StackTrace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Utilities.Misc.ExceptionHelpers.<WriteExceptionDetails>g__append|0_0(String prop, Func`2 fmt, <>c__DisplayClass0_0& )
   at Utilities.Misc.ExceptionHelpers.WriteExceptionDetails(StringBuilder builderToFill, Exception exception, Int32 level)
   at Utilities.Misc.ExceptionHelpers.ToStringAllExceptionDetails(Exception exception)
   at Utilities.Logging.Error(Exception ex, String msg, Object[] args)
   at Qiqqa.Documents.PDF.PDFControls.PDFExporting.ExportToWord.DoExport(PDFDocument pdf_document)
   at Qiqqa.Documents.PDF.PDFControls.PDFExporting.ExportToWord.ExportToTextAndLaunch(PDFDocument pdf_document)
   at Qiqqa.Documents.PDF.PDFControls.PDFReadingControl.ButtonExportToText_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
 System.Object = 
 === INNER EXCEPTION ===
 System.OutOfMemoryException
 Message: Exception of type 'System.OutOfMemoryException' was thrown.
 HResult: 0x8007000E
 Source: mscorlib
 StackTrace:    at System.String.Concat(String str0, String str1, String str2)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.get_StackTrace()
 TargetSite: System.String Concat(System.String, System.String, System.String)

20200324.095911 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [488.654M] DoMaintenance_Infrequent START
20200324.095911 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [488.692M] MetadataExtractionDaemon::DoMaintenance START
20200324.095911 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [488.700M] 1CBFAD8E774E9038986D74B79725232E5902ED9 requires PDFMetadataInferenceFromOCR
20200324.095911 [Q] INFO  [Main] [489.140M] About to display client stats: Something unexpected has happened, but it's okay. Exception has been thrown by the target of an invocation.
20200324.095912 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [489.070M] AutoSuggestMetadata:Suggesting metadata (4/4: 100.0%)
20200324.095912 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [489.467M] While autosuggesting title, OCR is still not ready for 1CBFAD8E774E9038986D74B79725232E5902ED9
20200324.095912 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [489.467M] Got 1 items of metadata extraction work done.
20200324.095912 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [489.467M] 552ms were spent to extract metadata
20200324.095912 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [489.467M] Rescan of library Library: Guest for indexing took 0ms for 21 documents.
20200324.095912 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [489.475M] Indexing document 1CBFAD8E774E9038986D74B79725232E5902ED9
20200324.095912 [Q] ERROR [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [488.733M] There was a problem while indexing document 1CBFAD8E774E9038986D74B79725232E5902ED9

System.OutOfMemoryException
Message: Exception of type 'System.OutOfMemoryException' was thrown.
HResult: 0x8007000E
Source: mscorlib
StackTrace:    at System.Text.StringBuilder..ctor(String value, Int32 startIndex, Int32 length, Int32 capacity)
   at Alphaleonis.Win32.Filesystem.Path.GetFullPathCore(KernelTransaction transaction, String path, GetFullPathOptions options)
   at Alphaleonis.Win32.Filesystem.Path.GetFullPathTackleCore(KernelTransaction transaction, String path, GetFullPathOptions options)
   at Qiqqa.Documents.PDF.PDFRendering.PDFRendererFileLayer.MakeFilenameWith2LevelIndirection(String file_type, Object token, String extension)
   at Qiqqa.Documents.PDF.PDFRendering.PDFRendererFileLayer.MakeFilename_TextSingle(Int32 page_number)
   at Qiqqa.Documents.PDF.PDFRendering.PDFRenderer.GetOCRText(Int32 page, Boolean queue_for_ocr)
   at Qiqqa.DocumentLibrary.DocumentLibraryIndex.LibraryIndex.IncrementalBuildNextDocuments()
TargetSite: Void .ctor(System.String, Int32, Int32, Int32)

20200324.095912 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [488.758M] Indexing document 44C644568DE3A7F3CB1962E644F19D5DCAE4E5D4
20200324.095913 [Q] ERROR [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [488.723M] There was a problem while indexing document 44C644568DE3A7F3CB1962E644F19D5DCAE4E5D4

System.OutOfMemoryException
Message: Exception of type 'System.OutOfMemoryException' was thrown.
HResult: 0x8007000E
Source: mscorlib
StackTrace:    at System.Text.StringBuilder..ctor(String value, Int32 startIndex, Int32 length, Int32 capacity)
   at Alphaleonis.Win32.Filesystem.Path.GetFullPathCore(KernelTransaction transaction, String path, GetFullPathOptions options)
   at Alphaleonis.Win32.Filesystem.Path.GetFullPathTackleCore(KernelTransaction transaction, String path, GetFullPathOptions options)
   at Qiqqa.Documents.PDF.PDFRendering.PDFRendererFileLayer.MakeFilenameWith2LevelIndirection(String file_type, Object token, String extension)
   at Qiqqa.Documents.PDF.PDFRendering.PDFRendererFileLayer.MakeFilename_TextGroup(Int32 page)
   at Qiqqa.Documents.PDF.PDFRendering.PDFRenderer.GetOCRText(Int32 page, Boolean queue_for_ocr)
   at Qiqqa.DocumentLibrary.DocumentLibraryIndex.LibraryIndex.IncrementalBuildNextDocuments()
TargetSite: Void .ctor(System.String, Int32, Int32, Int32)

20200324.095913 [Q] WARN  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [488.747M] LibraryIndex::IncrementalBuildNextDocuments: PDF document 44C644568DE3A7F3CB1962E644F19D5DCAE4E5D4: page 239 has no text (while pages 1-238,240-242,244,261,270-271,273-287,297,303,305,307,353,356,360,362,364-368,370-660,674-679,681-721 DO have text!) and will (re)trigger a PDF OCR action. This is probably a document which could not be OCRed properly (for reasons unknown at this time).
20200324.095913 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [488.771M] Incremental building of the library index for library Library: Guest took 823ms.
20200324.095913 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [488.771M] DoMaintenance_Infrequent END

------------------------------------------------------
COMMON STATISTICS:
Current version:       82
Current build:         82.0.7356.40890
Current path:          C:\Program Files (x86)\Util\Qiqqa
System path:           C:\Windows\system32
Command line:          "C:\Program Files (x86)\Util\Qiqqa\Qiqqa.exe"
OS version:            Microsoft Windows NT 6.2.9200.0
CPU count:             4
Machine name:          DESKTOP-S3KOT6N
CLR version:           4.8 or later (Full)  4.8.03752 (4.0.30319.42000)
Working set:           918Mb
Application data:      C:\Users\Nagesh\AppData\Roaming
Temp path:             C:\Users\Nagesh\AppData\Local\Temp\
CurrentCulture:        
CurrentUICulture:      en-US
CurrentUICulture.Name: en-US
InstalledUICulture:    en-US
InvariantCulture:      
UTC offset:            5.5
.NET4 client installed True
.NET4 full installed   True
.NET CLR versions installed:
- .NET version:         4.8 or later (Client)  4.8.03752
- .NET version:         4.8 or later (Full)  4.8.03752
- .NET version:         v4.0 (Client)  4.0.0.0
Application is not network deployed.
```

**Comment by GerHobbelt** [comment]
@raindropsfromsky : 

Thanks for the feedback: it's much appreciated that someone takes a precise look at it, even when it implies a lot of (dev) work. 👍 

---

Can you get me that huge PDF for testing? Haven't had a crash like that in ages. 😄

**Comment by raindropsfromsky** [comment]
Sure!
Here is the link
<https://drive.google.com/file/d/1y1Z6O_moXndlLJVOl1ZCR5xAzgtSqWzS/view?usp=sharing>
.

This compendium was created by Government of India, and made available
online.
I added bookmarks to it, and added a few explanatory comments (to guide the
environmental activists).

The original file is made of badly scanned documents.
Some of the pages are NOT in English (they are in Hindi).
(Can this be a factor in the crash?)

Wish you the best of luck in cracking this issue!

Regards
Narayan
