### ISSUE TITLE
Bug: Crash when speed-reading

### ISSUE THREAD

**Issue by raindropsfromsky** [jimmejardine/qiqqa-open-source#192]
While speed-reading the Supreme Court judgment, v82Pre8 crashed 
(OS: Win10 Home, 64 bit; i3 8th Gen, 12 GB DDR4 RAM)

**Problem summary**
Not enough quota is available to process this command
*************
**Exception trees**
20200327033927:System.ComponentModel.Win32Exception (0x80004005): Not enough quota is available to process this command
   at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

--------------------------------------------
**System logs**
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void PostMessage(System.Runtime.InteropServices.HandleRef, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
 System.Object = 

20200327.033927 [Q] INFO  [Main] [74.622M] About to display client stats: Something unexpected has happened, but it's okay. Not enough quota is available to process this command
20200327.033927 [Q] ERROR [Main] [82.638M] RemarkOnException.....

System.ComponentModel.Win32Exception
Message: Not enough quota is available to process this command
ErrorCode: 0x80004005
HResult: 0x80004005
Source: WindowsBase
StackTrace:    at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void PostMessage(System.Runtime.InteropServices.HandleRef, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
 System.Object = 

20200327.033927 [Q] ERROR [Main] [82.679M] RemarkOnException_GUI_THREAD...

System.ComponentModel.Win32Exception
Message: Not enough quota is available to process this command
ErrorCode: 0x80004005
HResult: 0x80004005
Source: WindowsBase
StackTrace:    at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void PostMessage(System.Runtime.InteropServices.HandleRef, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
 System.Object = 

20200327.033927 [Q] INFO  [Main] [74.759M] About to display client stats: Something unexpected has happened, but it's okay. Not enough quota is available to process this command
20200327.033927 [Q] ERROR [Main] [82.200M] RemarkOnException.....

System.ComponentModel.Win32Exception
Message: Not enough quota is available to process this command
ErrorCode: 0x80004005
HResult: 0x80004005
Source: WindowsBase
StackTrace:    at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void PostMessage(System.Runtime.InteropServices.HandleRef, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
 System.Object = 

20200327.033927 [Q] ERROR [Main] [82.233M] RemarkOnException_GUI_THREAD...

System.ComponentModel.Win32Exception
Message: Not enough quota is available to process this command
ErrorCode: 0x80004005
HResult: 0x80004005
Source: WindowsBase
StackTrace:    at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void PostMessage(System.Runtime.InteropServices.HandleRef, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
 System.Object = 

20200327.033927 [Q] INFO  [Main] [74.902M] About to display client stats: Something unexpected has happened, but it's okay. Not enough quota is available to process this command
20200327.033927 [Q] ERROR [Main] [82.939M] RemarkOnException.....

System.ComponentModel.Win32Exception
Message: Not enough quota is available to process this command
ErrorCode: 0x80004005
HResult: 0x80004005
Source: WindowsBase
StackTrace:    at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void PostMessage(System.Runtime.InteropServices.HandleRef, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
 System.Object = 

20200327.033927 [Q] ERROR [Main] [82.980M] RemarkOnException_GUI_THREAD...

System.ComponentModel.Win32Exception
Message: Not enough quota is available to process this command
ErrorCode: 0x80004005
HResult: 0x80004005
Source: WindowsBase
StackTrace:    at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void PostMessage(System.Runtime.InteropServices.HandleRef, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
 System.Object = 

20200327.033927 [Q] INFO  [Main] [75.034M] About to display client stats: Something unexpected has happened, but it's okay. Not enough quota is available to process this command
20200327.033927 [Q] ERROR [Main] [82.501M] RemarkOnException.....

System.ComponentModel.Win32Exception
Message: Not enough quota is available to process this command
ErrorCode: 0x80004005
HResult: 0x80004005
Source: WindowsBase
StackTrace:    at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void PostMessage(System.Runtime.InteropServices.HandleRef, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
 System.Object = 

20200327.033927 [Q] ERROR [Main] [82.542M] RemarkOnException_GUI_THREAD...

System.ComponentModel.Win32Exception
Message: Not enough quota is available to process this command
ErrorCode: 0x80004005
HResult: 0x80004005
Source: WindowsBase
StackTrace:    at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void PostMessage(System.Runtime.InteropServices.HandleRef, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
 System.Object = 

20200327.033927 [Q] INFO  [Main] [75.183M] About to display client stats: Something unexpected has happened, but it's okay. Not enough quota is available to process this command
20200327.033927 [Q] ERROR [Main] [83.224M] RemarkOnException.....

System.ComponentModel.Win32Exception
Message: Not enough quota is available to process this command
ErrorCode: 0x80004005
HResult: 0x80004005
Source: WindowsBase
StackTrace:    at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void PostMessage(System.Runtime.InteropServices.HandleRef, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
 System.Object = 

20200327.033927 [Q] ERROR [Main] [83.265M] RemarkOnException_GUI_THREAD...

System.ComponentModel.Win32Exception
Message: Not enough quota is available to process this command
ErrorCode: 0x80004005
HResult: 0x80004005
Source: WindowsBase
StackTrace:    at MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void PostMessage(System.Runtime.InteropServices.HandleRef, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
 System.Object = 

20200327.033927 [Q] INFO  [Main] [75.315M] About to display client stats: Something unexpected has happened, but it's okay. Not enough quota is available to process this command
-------------------------------------------------
**Machine stats:**
COMMON STATISTICS:
Current version:       82
Current build:         82.0.7356.40890
Current path:          C:\Program Files (x86)\Util\Qiqqa
System path:           C:\Windows\system32
Command line:          "C:\Program Files (x86)\Util\Qiqqa\Qiqqa.exe" 
OS version:            Microsoft Windows NT 6.2.9200.0
CPU count:             4
Machine name:          DESKTOP-S3KOT6N
CLR version:           4.8 or later (Full)  4.8.03752 (4.0.30319.42000)
Working set:           186Mb
Application data:      C:\Users\Nagesh\AppData\Roaming
Temp path:             C:\Users\Nagesh\AppData\Local\Temp\
CurrentCulture:        en-US
CurrentUICulture:      en-US
CurrentUICulture.Name: en-US
InstalledUICulture:    en-US
InvariantCulture:      
UTC offset:            5.5
.NET4 client installed True
.NET4 full installed   True
.NET CLR versions installed:
- .NET version:         4.8 or later (Client)  4.8.03752
- .NET version:         4.8 or later (Full)  4.8.03752
- .NET version:         v4.0 (Client)  4.0.0.0
Application is not network deployed.

**Comment by GerHobbelt** [comment]
Wow!

You've got some gold there! 

Please send all PDFs related to any crash you encounter to me; not via email as the large ones get lost (upper limit on email messages!); alternatively share the library via google drive or some other cloud service where it can be shared or downloaded.

Might be handy to also fetch and package the log files and upload to  the issue as well.

---



> (ripped off other issue response:)

I'm quite interested in your Qiqqa log files. You can find those at 

```
%appdata%\..\Local\Quantisle\Qiqqa\Logs
```

**Copy that path into your Windows Explorer as shown below and you'll be redirected to your AppData dirtree where Qiqqa keeps it log files, as shown in  the screenshot below.**

![2020-03-27_10-28-14](https://user-images.githubusercontent.com/402462/77741971-02653500-7016-11ea-9a77-ec023cb0c9d2.png)

**Comment by raindropsfromsky** [comment]
Shared via Google Drive. Please check your mail. Thanks!

**Comment by GerHobbelt** [comment]
Commit SHA-1: fc50dfd3454795e8e6b17cc4a87ffd43f40cdd30

* Crashes fixed (AFAICT). https://github.com/jimmejardine/qiqqa-open-source/issues/192

Also fixed: dropdown menu used to open/invoke the Speed Reader Window for a given document did not close/disappear immediately after click. Now it does.

Also fixed: the QiqqaOCR/pdfdraw/tesseract3 Text Extraction & OCR tools will often spit out text that includes words which are all-whitespace. These are filtered out before feeding the text to the Speed Reader. (An improved Text Extract system is being working on over at the MuPDF tooling repo, but that will take some time before it will deployable. This minor house-cleaning approach will have to suffice till then.

Also *augmented* the Speed Reader: added choice between WPM (Words Per Minute) and CPM (Characters Per Minute). The latter is handy when you push the edge of your reading speed as your eyes generally need more time to scan long words than short ones, while the short ones (except maybe 'a', 'the', etc.) are as important as the long ones in a text.

**Aside**: I know CPM isn't exactly representative of how humans scan/read text. PPM (**Phonemes Per Minute**) MAY be a bit closer but brain / eye-movement research has, IIRC, observed a more 'fluid' method, where humans recognize entire word or partial word patterns at once. Anyway, for those interested in using or testing this, CPM mode has been added. Sliders / Speed will adjust automatically when you flip between the WPM & CPM modes (at a ratio of 1:7)

---

To be made available in the next release.

**Comment by GerHobbelt** [comment]
Screenshot of the augmented UI:

![image](https://user-images.githubusercontent.com/402462/120720735-e0dec380-c4cc-11eb-856d-743bd7367665.png)

**Comment by GerHobbelt** [comment]
Related: #191 (feature req; not done yet)
