### ISSUE TITLE
Bug: Crash when extracting annotation

### ISSUE THREAD

**Issue by raindropsfromsky** [jimmejardine/qiqqa-open-source#195]
**Summary:**
Operation is not valid while ItemsSource is in use. Access and modify elements with ItemsControl.ItemsSource instead.

**Exception trees:**
20200327052744:System.InvalidOperationException: Operation is not valid while ItemsSource is in use. Access and modify elements with ItemsControl.ItemsSource instead.
   at System.Windows.Controls.ItemCollection.Clear()
   at Qiqqa.AnnotationsReportBuilding.AnnotationReportOptionsWindow.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

--------------------------------------------
**Recent logs:**
20200327.052649 [Q] DEBUG [4] [5.037M] LibraryInitialLoad:Loading your library 'Guest': 17 of 21 documents (17/21: 81.0%)
20200327.052649 [Q] INFO  [4] [5.045M] Library 'Guest': Loaded 17/21 documents
20200327.052649 [Q] DEBUG [4] [5.054M] LibraryInitialLoad:Loading your library 'Guest': 18 of 21 documents (18/21: 85.7%)
20200327.052649 [Q] INFO  [4] [5.054M] Library 'Guest': Loaded 18/21 documents
20200327.052649 [Q] DEBUG [4] [5.062M] LibraryInitialLoad:Loading your library 'Guest': 19 of 21 documents (19/21: 90.5%)
20200327.052649 [Q] INFO  [4] [5.062M] Library 'Guest': Loaded 19/21 documents
20200327.052649 [Q] DEBUG [4] [5.160M] LibraryInitialLoad:Loading your library 'Guest': 20 of 21 documents (20/21: 95.2%)
20200327.052649 [Q] INFO  [4] [5.160M] Library 'Guest': Loaded 20/21 documents
20200327.052649 [Q] DEBUG [4] [5.176M] -Build library 'Guest' from repository -- time spent: 248 ms on 21 library records.
20200327.052649 [Q] INFO  [4] [5.792M] +Saving known Web Libraries to C:\Users\Nagesh\AppData\Local\Quantisle\Qiqqa\Guest\Qiqqa.known_web_libraries
20200327.052649 [Q] DEBUG [7] [5.988M] BulkLibraryDocument:Adding document 1 of 1 to your library (0/1: 0.0%)
20200327.052649 [Q] INFO  [4] [7.074M] -Saving known Web Libraries to C:\Users\Nagesh\AppData\Local\Quantisle\Qiqqa\Guest\Qiqqa.known_web_libraries
20200327.052649 [Q] INFO  [4] [7.082M] +Notifying everyone that web libraries have changed
20200327.052649 [Q] INFO  [4] [7.082M] -Notifying everyone that web libraries have changed
20200327.052649 [Q] INFO  [7] [7.114M] Fingerprint: 60835FB1D237D8F3ED73653CC9F935FDD7FA16B1 - add to library: False
20200327.052649 [Q] INFO  [Main] [5.961M] Loaded assembly: Syncfusion.Chart.Wpf, Version=17.1400.0.38, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89
20200327.052649 [Q] INFO  [Main] [6.043M] Loaded assembly: Syncfusion.Shared.Wpf, Version=17.1400.0.38, Culture=neutral, PublicKeyToken=3d67ed1f87d44c89
20200327.052650 [Q] INFO  [Main] [10.600M] Loaded 17 BibTeX entry types from configuration file 'C:\Program Files (x86)\Util\Qiqqa\BibTeX\EntryTypeDefinitions\qiqqa-entry-type-definitions.json':
    [article, book, booklet, conference, inbook, chapter, incollection, inproceedings, manual, mastersthesis, misc, phdthesis, proceedings, techreport, unpublished, webpage, legal_case]
20200327.052650 [Q] INFO  [Main] [11.354M] Loaded assembly: WPFToolkit.Extended, Version=1.6.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4
20200327.052650 [Q] INFO  [Main] [10.239M] Loaded assembly: WindowsFormsIntegration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
20200327.052650 [Q] INFO  [Main] [9.646M] +Getting node items for Tags
20200327.052650 [Q] DEBUG [Main] [9.646M] TagExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] INFO  [Main] [9.687M] -Getting node items
20200327.052650 [Q] INFO  [Main] [9.711M] Loaded assembly: Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
20200327.052650 [Q] DEBUG [Main] [9.946M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] INFO  [Main] [9.946M] +Getting node items for AutoTags
20200327.052650 [Q] DEBUG [Main] [9.954M] AITagExplorerControl: processing 0 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [9.979M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] INFO  [Main] [9.979M] +Getting node items for Authors
20200327.052650 [Q] DEBUG [Main] [9.979M] AuthorExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] INFO  [Main] [9.987M] -Getting node items
20200327.052650 [Q] DEBUG [Main] [10.044M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [10.044M] PublicationExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [10.069M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [10.077M] ReadingStageExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [10.102M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [10.102M] YearExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [10.184M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [10.192M] RatingExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [10.216M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] INFO  [Main] [11.206M] +Loading Expedition: C:\Users\Nagesh\AppData\Local\Quantisle\Qiqqa\Guest\Qiqqa.expedition
20200327.052650 [Q] INFO  [Main] [11.852M] -Loading Expedition
20200327.052650 [Q] INFO  [Main] [11.852M] +Generating density_of_words_in_topics
20200327.052650 [Q] INFO  [Main] [11.869M] -Generating density_of_words_in_topics
20200327.052650 [Q] INFO  [Main] [11.869M] +Generating density_of_topics_in_documents
20200327.052650 [Q] INFO  [Main] [11.877M] -Generating density_of_topics_in_documents
20200327.052650 [Q] DEBUG [Main] [11.926M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [11.926M] TypeExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [11.975M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [11.992M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] INFO  [Main] [11.992M] +Getting node items for Tags
20200327.052650 [Q] DEBUG [Main] [11.992M] TagExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] INFO  [Main] [12.024M] -Getting node items
20200327.052650 [Q] DEBUG [Main] [12.237M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] INFO  [Main] [12.237M] +Getting node items for AutoTags
20200327.052650 [Q] DEBUG [Main] [12.237M] AITagExplorerControl: processing 0 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [12.262M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] INFO  [Main] [12.262M] +Getting node items for Authors
20200327.052650 [Q] DEBUG [Main] [12.262M] AuthorExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] INFO  [Main] [12.270M] -Getting node items
20200327.052650 [Q] DEBUG [Main] [12.344M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [12.344M] PublicationExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [12.368M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [12.377M] ReadingStageExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [12.401M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [12.401M] YearExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [12.516M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [12.516M] RatingExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [12.540M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [12.606M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [12.606M] TypeExplorerControl: processing 4 documents from library Guest
20200327.052650 [Q] DEBUG [Main] [12.663M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] DEBUG [Main] [12.663M] ReviewParameters: 4 documents to process for library Guest
20200327.052650 [Q] INFO  [Main] [13.229M] OpenLibrary: Library Guest has 21 documents loaded
20200327.052650 [Q] WARN  [5] [13.237M] Finished restoring desktop.
20200327.052650 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_OnceOff] [10.743M] -MaintainableManager was waiting some startup time for Qiqqa.Common.BackgroundWorkerDaemonStuff.BackgroundWorkerDaemon:DoMaintenance_OnceOff
20200327.052650 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_OnceOff] [10.800M] DoMaintenance_OnceOff START
20200327.052650 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_OnceOff] [11.550M] About to check for new client version at server: http://download.qiqqa.com/Content/Client/ClientVersion.xml
20200327.052650 [Q] INFO  [Main] [15.392M] ShutdownableManager is registering Qiqqa.Documents.Common.DocumentQueuedStorer
20200327.052650 [Q] DEBUG [7] [11.404M] BulkLibraryDocument:Added 1 of 1 document(s) to your library (0/0: 0.0%)
20200327.052650 [Q] DEBUG [7] [11.404M] AddNewPDFDocumentsToLibraryFromFolder_SYNCHRONOUS: time spent: 816 ms
20200327.052650 [Q] DEBUG [7] [11.606M] BulkLibraryDocument:Adding document 1 of 1 to your library (0/1: 0.0%)
20200327.052650 [Q] DEBUG [Main] [11.999M] Screen position and window size parsing 10.4|10.4|1024|700|Maximized to 10.4,10.4,1024,700 ...
20200327.052650 [Q] INFO  [Main] [12.022M] Window QiqqaMainWindow: Screen position and window size restoring to x=10.4,y=10.4,w=1024,h=700,mode=Maximized
20200327.052650 [Q] INFO  [7] [13.087M] Fingerprint: 3752B65FCBD0A227B0A19673F03D3D7D52B58A - add to library: False
20200327.052650 [Q] DEBUG [7] [13.856M] BulkLibraryDocument:Added 1 of 1 document(s) to your library (0/0: 0.0%)
20200327.052650 [Q] DEBUG [7] [13.856M] AddNewPDFDocumentsToLibraryFromFolder_SYNCHRONOUS: time spent: 321 ms
20200327.052650 [Q] ERROR [18] [13.909M] Error while processing pipe connection. (Qiqqa.Startup.Comms)

System.ObjectDisposedException
Message: Cannot access a closed pipe.
HResult: 0x80131622
Source: System.Core
StackTrace:    at System.IO.__Error.PipeNotOpen()
   at System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServer()
   at System.IO.Pipes.NamedPipeServerStream.EndWaitForConnection(IAsyncResult asyncResult)
   at Qiqqa.Main.IPC.IPCServer.<StartServerPump>b__8_0(IAsyncResult async_result)
TargetSite: Void PipeNotOpen()

20200327.052650 [Q] DEBUG [4] [16.409M] +Initialising SoraxPDFRendererDLLWrapper
20200327.052650 [Q] DEBUG [4] [16.417M] -Initialising SoraxPDFRendererDLLWrapper
20200327.052651 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_OnceOff] [15.672M] Loaded assembly: Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
20200327.052651 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_OnceOff] [16.019M] Received latest client version information from server: LatestVersion: 79, CompliantFromVersion: 79, ObsoleteToVersion: , DownloadLocations: @WEB_BASE@
20200327.052651 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_OnceOff] [16.027M] User is running an old version (v82), but it is still >= the compliant version (v79), so not telling them to update.
20200327.052651 [Q] WARN  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_OnceOff] [16.027M] Current executing version (v82) is ahead of server version (v79)??? Have we rolled back a version?
20200327.052651 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_OnceOff] [16.428M] Checking for Dropbox conflicts in C:\Users\Nagesh\AppData\Local\Quantisle\Qiqqa for machine DESKTOP-S3KOT6N
20200327.052651 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_OnceOff] [17.469M] Mendeley not found.
20200327.052652 [Q] INFO  [Daemon.Maintainable:FolderWatcherManager.TaskDaemonEntryPoint.Lib(Library: Guest)] [17.535M] +MaintainableManager is waiting some startup time (30000ms) for Qiqqa.DocumentLibrary.FolderWatching.FolderWatcherManager:TaskDaemonEntryPoint.Lib(Library: Guest)
20200327.052652 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Frequent] [17.568M] +MaintainableManager is waiting some startup time (10000ms) for Qiqqa.Common.BackgroundWorkerDaemonStuff.BackgroundWorkerDaemon:DoMaintenance_Frequent
20200327.052652 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_VeryInfrequent] [17.568M] +MaintainableManager is waiting some startup time (10000ms) for Qiqqa.Common.BackgroundWorkerDaemonStuff.BackgroundWorkerDaemon:DoMaintenance_VeryInfrequent
20200327.052652 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_QuiteInfrequent] [17.568M] +MaintainableManager is waiting some startup time (10000ms) for Qiqqa.Common.BackgroundWorkerDaemonStuff.BackgroundWorkerDaemon:DoMaintenance_QuiteInfrequent
20200327.052652 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.568M] +MaintainableManager is waiting some startup time (10000ms) for Qiqqa.Common.BackgroundWorkerDaemonStuff.BackgroundWorkerDaemon:DoMaintenance_Infrequent
20200327.052652 [Q] INFO  [Daemon.Maintainable:DocumentQueuedStorer.DoMaintenance_FlushDocuments] [17.576M] +MaintainableManager is waiting some startup time (30000ms) for Qiqqa.Documents.Common.DocumentQueuedStorer:DoMaintenance_FlushDocuments
20200327.052702 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [16.460M] -MaintainableManager was waiting some startup time for Qiqqa.Common.BackgroundWorkerDaemonStuff.BackgroundWorkerDaemon:DoMaintenance_Infrequent
20200327.052702 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_VeryInfrequent] [16.460M] -MaintainableManager was waiting some startup time for Qiqqa.Common.BackgroundWorkerDaemonStuff.BackgroundWorkerDaemon:DoMaintenance_VeryInfrequent
20200327.052702 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_QuiteInfrequent] [16.476M] -MaintainableManager was waiting some startup time for Qiqqa.Common.BackgroundWorkerDaemonStuff.BackgroundWorkerDaemon:DoMaintenance_QuiteInfrequent
20200327.052702 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Frequent] [16.476M] -MaintainableManager was waiting some startup time for Qiqqa.Common.BackgroundWorkerDaemonStuff.BackgroundWorkerDaemon:DoMaintenance_Frequent
20200327.052702 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_QuiteInfrequent] [16.476M] DoMaintenance_QuiteInfrequent START
20200327.052702 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [16.476M] DoMaintenance_Infrequent START
20200327.052702 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_VeryInfrequent] [16.476M] DoMaintenance_VeryInfrequent START
20200327.052702 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [16.476M] MetadataExtractionDaemon::DoMaintenance START
20200327.052702 [Q] DEBUG [Main] [16.492M] ReviewParameters: 4 documents to process for library Guest
20200327.052702 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [16.509M] MetadataExtractionDaemon::DoMaintenance: Breaking out of outer processing loop due to no more files to process right now.
20200327.052702 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [16.509M] 11ms were spent to extract metadata
20200327.052702 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.138M] Try to load a historical progress file: C:\Users\Nagesh\AppData\Local\Quantisle\Qiqqa\Guest\index\DocumentProgressList.dat
20200327.052702 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [16.485M] +Loading historical progress file: C:\Users\Nagesh\AppData\Local\Quantisle\Qiqqa\Guest\index\DocumentProgressList.dat
20200327.052702 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.894M] -Loaded historical progress file: C:\Users\Nagesh\AppData\Local\Quantisle\Qiqqa\Guest\index\DocumentProgressList.dat (time spent: 6 ms)
20200327.052702 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [18.122M] Loaded assembly: Lucene.Net, Version=2.9.4.1, Culture=neutral, PublicKeyToken=85089178b9ac3181
20200327.052702 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [19.930M] +Flushing a lucene IndexWriter
20200327.052702 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [19.930M] -Flushing a lucene IndexWriter (time spent: 0 ms)
20200327.052702 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [19.938M] Incremental building of the library index for library Library: Guest took 0ms.
20200327.052702 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [19.938M] DoMaintenance_Infrequent END
20200327.052712 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.682M] DoMaintenance_Infrequent START
20200327.052712 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.682M] MetadataExtractionDaemon::DoMaintenance START
20200327.052712 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.682M] MetadataExtractionDaemon::DoMaintenance: Breaking out of outer processing loop due to no more files to process right now.
20200327.052712 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.682M] 0ms were spent to extract metadata
20200327.052712 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.682M] Incremental building of the library index for library Library: Guest took 0ms.
20200327.052712 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.690M] DoMaintenance_Infrequent END
20200327.052722 [Q] INFO  [Daemon.Maintainable:FolderWatcherManager.TaskDaemonEntryPoint.Lib(Library: Guest)] [16.979M] -MaintainableManager was waiting some startup time for Qiqqa.DocumentLibrary.FolderWatching.FolderWatcherManager:TaskDaemonEntryPoint.Lib(Library: Guest)
20200327.052722 [Q] DEBUG [Daemon.Maintainable:FolderWatcherManager.TaskDaemonEntryPoint.Lib(Library: Guest)] [16.979M] FolderWatcherTask for library Library: Guest START
20200327.052722 [Q] INFO  [Daemon.Maintainable:DocumentQueuedStorer.DoMaintenance_FlushDocuments] [16.987M] -MaintainableManager was waiting some startup time for Qiqqa.Documents.Common.DocumentQueuedStorer:DoMaintenance_FlushDocuments
20200327.052722 [Q] DEBUG [Daemon.Maintainable:DocumentQueuedStorer.DoMaintenance_FlushDocuments] [16.987M] DocumentQueuedStorer:2/2 documents still to flush (0/2: 0.0%)
20200327.052722 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.166M] DoMaintenance_Infrequent START
20200327.052722 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.166M] MetadataExtractionDaemon::DoMaintenance START
20200327.052722 [Q] DEBUG [Daemon.Maintainable:DocumentQueuedStorer.DoMaintenance_FlushDocuments] [17.248M] DocumentQueuedStorer:1/2 documents still to flush (1/2: 50.0%)
20200327.052722 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.248M] MetadataExtractionDaemon::DoMaintenance: Breaking out of outer processing loop due to no more files to process right now.
20200327.052722 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.248M] 23ms were spent to extract metadata
20200327.052722 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.248M] Incremental building of the library index for library Library: Guest took 0ms.
20200327.052722 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [17.256M] DoMaintenance_Infrequent END
20200327.052732 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [19.991M] DoMaintenance_Infrequent START
20200327.052732 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [19.991M] MetadataExtractionDaemon::DoMaintenance START
20200327.052732 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [19.991M] MetadataExtractionDaemon::DoMaintenance: Breaking out of outer processing loop due to no more files to process right now.
20200327.052732 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [19.991M] 0ms were spent to extract metadata
20200327.052732 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [19.991M] Incremental building of the library index for library Library: Guest took 0ms.
20200327.052732 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [20.000M] DoMaintenance_Infrequent END
20200327.052742 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [18.739M] DoMaintenance_Infrequent START
20200327.052742 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [18.739M] MetadataExtractionDaemon::DoMaintenance START
20200327.052742 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [18.739M] MetadataExtractionDaemon::DoMaintenance: Breaking out of outer processing loop due to no more files to process right now.
20200327.052742 [Q] INFO  [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [18.739M] 0ms were spent to extract metadata
20200327.052742 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [18.739M] Incremental building of the library index for library Library: Guest took 0ms.
20200327.052742 [Q] DEBUG [Daemon.Maintainable:BackgroundWorkerDaemon.DoMaintenance_Infrequent] [18.747M] DoMaintenance_Infrequent END
20200327.052744 [Q] DEBUG [Main] [19.205M] AnnotationReport:Initialising annotation report (0/4: 0.0%)
20200327.052744 [Q] ERROR [Main] [18.044M] RemarkOnException.....

System.InvalidOperationException
Message: Operation is not valid while ItemsSource is in use. Access and modify elements with ItemsControl.ItemsSource instead.
HResult: 0x80131509
Source: PresentationFramework
StackTrace:    at System.Windows.Controls.ItemCollection.Clear()
   at Qiqqa.AnnotationsReportBuilding.AnnotationReportOptionsWindow.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void Clear()
 System.Object = 

20200327.052744 [Q] ERROR [Main] [18.077M] RemarkOnException_GUI_THREAD...

System.InvalidOperationException
Message: Operation is not valid while ItemsSource is in use. Access and modify elements with ItemsControl.ItemsSource instead.
HResult: 0x80131509
Source: PresentationFramework
StackTrace:    at System.Windows.Controls.ItemCollection.Clear()
   at Qiqqa.AnnotationsReportBuilding.AnnotationReportOptionsWindow.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
TargetSite: Void Clear()
 System.Object = 

20200327.052744 [Q] INFO  [Main] [15.888M] About to display client stats: Something unexpected has happened, but it's okay. Operation is not valid while ItemsSource is in use. Access and modify elements with ItemsControl.ItemsSource instead.
---------------------------------------------------
**Machine stats:**
COMMON STATISTICS:
Current version:       82
Current build:         82.0.7356.40890
Current path:          C:\Program Files (x86)\Util\Qiqqa
System path:           C:\Windows\system32
Command line:          "C:\Program Files (x86)\Util\Qiqqa\Qiqqa.exe" 
OS version:            Microsoft Windows NT 6.2.9200.0
CPU count:             4
Machine name:          DESKTOP-S3KOT6N
CLR version:           4.8 or later (Full)  4.8.03752 (4.0.30319.42000)
Working set:           148Mb
Application data:      C:\Users\Nagesh\AppData\Roaming
Temp path:             C:\Users\Nagesh\AppData\Local\Temp\
CurrentCulture:        en-US
CurrentUICulture:      en-US
CurrentUICulture.Name: en-US
InstalledUICulture:    en-US
InvariantCulture:      
UTC offset:            5.5
.NET4 client installed True
.NET4 full installed   True
.NET CLR versions installed:
- .NET version:         4.8 or later (Client)  4.8.03752
- .NET version:         4.8 or later (Full)  4.8.03752
- .NET version:         v4.0 (Client)  4.0.0.0
Application is not network deployed.

**Comment by GerHobbelt** [comment]
Finally this crash has been addressed and is available in the new prerelease: https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v82.0.7555-31312

P.S.: there's more trouble abound in the Annotations Report I believe as my own tests didn't produce the annotation reports I would expect, but empty reports instead. To be addressed next, I guess. 🤔
