### ISSUE TITLE
PDF OCR errors to investigate...

### ISSUE THREAD

**Issue by GerHobbelt** [jimmejardine/qiqqa-open-source#25]
I've seen all sorts of things go wrong with PDFs, but these should be dealt with more or less sensibly (as far as you can deal *sensibly* with a *garbage input*).

At least Qiqqa & QiqqaOCR [MUST NOT](https://tools.ietf.org/html/rfc2119) crash, lock up or otherwise *b0rk* on bad input PDFs.

Debug log extract:

```
20190804.204323 ERROR [PDFTextExtractor] There was a problem while running OCR with parameters: GROUP "D:\Qiqqa\base\Guest\documents\9\97F3C6565FB76E8DF535D150CB43D08EC2E62517.pdf" 301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320 "C:\Users\Ger\AppData\Local\Temp\\TempFile.dd76b1ad-93ef-44fe-93e0-f5d0fa5f25ec.txt" "" ""
20190804.204323 INFO  [PDFTextExtractor] Parameters: GROUP "D:\Qiqqa\base\Guest\documents\9\97F3C6565FB76E8DF535D150CB43D08EC2E62517.pdf" 301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320 "C:\Users\Ger\AppData\Local\Temp\\TempFile.dd76b1ad-93ef-44fe-93e0-f5d0fa5f25ec.txt" "" ""
20190804.204323 INFO  [PDFTextExtractor] --- Standard output:
20190804.204322 INFO  [Main] Logging initialised
20190804.204322 INFO  [Main] Starting the text extract thread
20190804.204323 INFO  [Main] Both text extract and OCR have exited, so exiting
20190804.204323 ERROR [Main] There was an error in QiqqaOCR:
--- Parameters ---
GROUP D:\Qiqqa\base\Guest\documents\9\97F3C6565FB76E8DF535D150CB43D08EC2E62517.pdf 301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320 C:\Users\Ger\AppData\Local\Temp\\TempFile.dd76b1ad-93ef-44fe-93e0-f5d0fa5f25ec.txt   
--- Exception ---
System.Exception: We have no wordlist to write!
   at QiqqaOCR.TextExtractEngine.MainEntry(String[] args, Boolean no_kill) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\QiqqaOCR\TextExtractEngine.cs:line 111
   at QiqqaOCR.Program.Main(String[] args) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\QiqqaOCR\Program.cs:line 46


System.Exception: We have no wordlist to write!
   at QiqqaOCR.TextExtractEngine.MainEntry(String[] args, Boolean no_kill) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\QiqqaOCR\TextExtractEngine.cs:line 111
   at QiqqaOCR.Program.Main(String[] args) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\QiqqaOCR\Program.cs:line 46

--- Standard error:


```

**Comment by GerHobbelt** [comment]
Related: #74

**Comment by GerHobbelt** [comment]
The last weeks have seen a lot of activity to make the code more roust. That part of this issue is therefore considered fixed.

The crashes that do happen still are due to corrupted PDFs and other PDF library related issues. The remainder of this issue is represented in #95.

Closing this as the work has been done dev repo for v82 release: https://github.com/GerHobbelt/qiqqa-open-source/tree/v82-build
