### ISSUE TITLE
Did not understand how to queue upload PDFs for library  

### ISSUE THREAD

**Issue by hazhiriq** [jimmejardine/qiqqa-open-source#279]
20201225144831:System.Exception: Did not understand how to queue upload PDFs for library Proposal_PhD Library
   at Qiqqa.Synchronisation.BusinessLogic.LibrarySyncManager.SynchronizeDocuments_Upload_INTERNAL_BACKGROUND(WebLibraryDetail web_library_detail, List`1 pdf_documents, Boolean is_readonly)
   at Qiqqa.Synchronisation.BusinessLogic.LibrarySyncManager.Sync_BACKGROUND(SyncControlGridItem sync_control_grid_item)
   at Qiqqa.Synchronisation.BusinessLogic.LibrarySyncManager.<>c__DisplayClass7_0.<Sync>b__0(Object o)
   at Utilities.Misc.SafeThreadPool.UserWorkItem(WaitCallback callback, Boolean skip_at_app_shutdown)

--------------------------------------------

**Comment by GerHobbelt** [comment]
Did a quick code inspection: this is a report from Qiqqa about non-InTRAnet libraries which it was instructed to *synchronize*.

Do you happen to have Qiqqa Cloud (a.k.a. "Web") libraries from back when Qiqqa was a commercial product?

Which version of Qiqqa are you currently using?

**Comment by dawei238** [comment]
I am facing the same issue.
I have had Qiqqa Cloud and, currently using the v.82.
Thanks

**Comment by GerHobbelt** [comment]
@dawei238  
Please note this part of the main README: https://github.com/jimmejardine/qiqqa-open-source#web-libraries-commercial-qiqqa-cloud-storage-will-be-discontinued-at-the-end-of-2020

Short version of the process to follow:

1. if you worry about your **local** libraries' copy to be **older** than your Qiqqa Cloud copy (because you collaborate with others or otherwise suspect that the *last work done* on the library happened on a different machine than the one you're currently at:
  
  Install commercial Qiqqa v79 and pray that you still have Cloud access. SYNC your libraries, so your **local copy** gets updated.

2. When you're convinced your local machine has the most recent work, the Qiqqa Cloud store is irrelevant and you can install an open source Qiqqa. 

  Advised version today: https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v82.0.7568-29227

3. install can simply overwrite the older Qiqqa: you can do that with any Qiqqa version from v79 - v83 at least as they are all binary compatible.
4. Start Qiqqa: it will take a while after you click the big Start button

  ![image](https://user-images.githubusercontent.com/402462/105767957-fca0ee80-5f5b-11eb-8987-76309d26bea0.png)

  as Qiqqa will be scanning your Libraries Base directory (a.k.a. Qiqqa Base Path) looking for your libraries.

  Once it has discovered all libraries you have in there, including your 'Cloud based' libraries from the days of Commercial Qiqqa, it will list them all in the Home tab.

  **Note** that some Commercial Qiqqa libraries MAY show up with slightly cryptic means, if you ever had crashes or other failures with Commercial Qiqqa.

  Anyway, all your libraries should now be accessible and clicking on them should the list of documents contained in each, as you're used to.

**Comment by dawei238** [comment]
Many thanks, I appreciate this. I will try it.
