### ISSUE TITLE
✅ odd "INFO [Main] Object reference not set to an instance of an object." lines in Qiqqa logfile.

### ISSUE THREAD

**Issue by GerHobbelt** [jimmejardine/qiqqa-open-source#28]

**Comment by GerHobbelt** [comment]
Sample log output after augmentation as per commit SHA-1: e58df0ae36e9b55429c0b51e79f82af08edd695c

```
20190807.095336 INFO  [Main] [149.956956] Object reference not set to an instance of an object.
  Stacktrace:
       at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
       at System.Environment.get_StackTrace()
       at Utilities.Logging.AppendStackTrace(String message) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\Utilities\Logging.cs:line 33
       at Utilities.Logging.Info(String msg) in W:\Users\Ger\Projects\sites\library.visyond.gov\80\lib\tooling\qiqqa\Utilities\Logging.cs:line 58
       at Qiqqa.Documents.PDF.PDFControls.MetadataControls.GoogleBibTexSnifferControl.ReflectLatestBrowserContent()
       at Qiqqa.Documents.PDF.PDFControls.MetadataControls.GoogleBibTexSnifferControl.ObjWebBrowser_PageLoaded()
       at Qiqqa.WebBrowsing.WebBrowserHostControl.ObjWebBrowser_LoadCompleted(WebBrowserControl wbc)
       at Qiqqa.WebBrowsing.WebBrowserControl.ObjWebBrowser_DocumentCompleted(Object sender, EventArgs e)
       at Gecko.GeckoWebBrowser.OnDocumentCompleted(GeckoDocumentCompletedEventArgs e) in c:\Users\hindlet\Documents\Visual Studio 2012\Projects\geckofx-33.0\Geckofx-Winforms\GeckoWebBrowser.Events.cs:line 257
       at Gecko.GeckoWebBrowser.Gecko.nsIWebProgressListener.OnStateChange(nsIWebProgress aWebProgress, nsIRequest aRequest, UInt32 aStateFlags, Int32 aStatus) in c:\Users\hindlet\Documents\Visual Studio 2012\Projects\geckofx-33.0\Geckofx-Winforms\GeckoWebBrowser.cs:line 1698
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at System.Windows.Application.Run()
       at Qiqqa.Main.MainEntry.Main()
```

**Comment by GerHobbelt** [comment]
Done as per #33.

Main Commits:

Revision: 271792422c28c77546839849f527cc43708c7cbf
Merge branch 'work'

Revision: 785c4879e195a96b1784bf194ecfc73aac8fe3d2
fix https://github.com/jimmejardine/qiqqa-open-source/issues/28: turns out Qiqqa is feeding all the empty records to the PubMed-to-BibTex converter, which is throwing a tantrum. Improved checks and balances and all that. Jolly good, carry on, chaps. :-)

**Comment by GerHobbelt** [comment]
> Closing <sup>and decluttering the issue list so it stays workable for me</sup>: fixed in https://github.com/GerHobbelt/qiqqa-open-source mainline=master branch, pending #15 / any maintainer rights/actions.
