### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by vcoyne1** [jimmejardine/qiqqa-open-source#308]
The application freezes/becomes unresponsive. Recovers if I attempt to close the application via the Qiqqa icon on the taskbar (close all windows).

[!Qiqqa.ErrorsAndUserActions.log](https://github.com/jimmejardine/qiqqa-open-source/files/6075944/Qiqqa.ErrorsAndUserActions.log)

**Comment by GerHobbelt** [comment]
Which version are you running, by the way?

Looks like you're running one of the experimental v83 releases. As a work-around you might be best served with installing the last v82 release and trying again.

**Comment by vcoyne1** [comment]
Hi,

Yes, running v83. I'll revert to v 82 until this issue is resolved.

Cheers,
Vernon

**Comment by SimonDedman** [comment]
Same issue for v83s, full error info:

20230329214913:System.NullReferenceException: Object reference not set to an instance of an object.
   at Qiqqa.Documents.PDF.PDFControls.Page.Highlight.PDFHighlightLayer.PDFHighlightLayer_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
