### ISSUE TITLE
Qiqqa PDF rendering error: PDF resize failed

### ISSUE THREAD

**Issue by GerHobbelt** [jimmejardine/qiqqa-open-source#9]
From the debug stats log (v80 github release on Windows 10/64):

> 20190730.192655 ERROR [39] There was an error while resizing a PDF page image
>
> Utilities.GenericException: Error while rasterising page 1 at 187.5dpi of 'D:\Qiqqa\base\Guest\documents\2\26ABFE782ECFA6E4ACC9F93138A353B6F3126.pdf' --->
> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
>    at Utilities.PDF.Sorax.SoraxDLL.SPD_GetPageBitmap(IntPtr hDoc, IntPtr hDC, Int32 nPage, Int32 nRot, Single fDPI)
>    at Utilities.PDF.Sorax.SoraxPDFRendererDLLWrapper.GetPageByDPIAsImage_LOCK(HDOCWrapper hdoc, Int32 page, Single dpi)
>    --- End of inner exception stack trace ---
>    at Utilities.PDF.Sorax.SoraxPDFRendererDLLWrapper.GetPageByDPIAsImage_LOCK(HDOCWrapper hdoc, Int32 page, Single dpi)
>    at Utilities.PDF.Sorax.SoraxPDFRendererDLLWrapper.GetPageByHeightAsImage(String filename, String pdf_user_password, String pdf_owner_password, Int32 page, Double height)
>    at Utilities.PDF.Sorax.SoraxPDFRenderer.GetPageByHeightAsImage(Int32 page, Double height)
>    at Qiqqa.Documents.PDF.PDFControls.PDFRendererControlStats.ResizedPageImageItemThreadEntry(Object arg)

**Comment by GerHobbelt** [comment]
Adobe Acrobat DC reports an error on the PDF as well.

**Comment by GerHobbelt** [comment]
[26ABFE782ECFA6E4ACC9F93138A353B6F3126.pdf](https://github.com/jimmejardine/qiqqa-open-source/files/3448659/26ABFE782ECFA6E4ACC9F93138A353B6F3126.pdf)

The offending PDF from the Qiqqa `Guest/documents/2` directory.

**Comment by GerHobbelt** [comment]
Other example PDF files which do not size correctly in the GoogleSniffer window: (these scale correctly if you jiggle the splitter-bar between bibtex and PDF viewer panes left&right a little)

[7B599A0AAFA19F0AE415129A185AB13FA42A3.pdf](https://github.com/jimmejardine/qiqqa-open-source/files/3512418/7B599A0AAFA19F0AE415129A185AB13FA42A3.pdf)

[C7A730925F25BA3DA70B0F7A21CD2B08EEE27.pdf](https://github.com/jimmejardine/qiqqa-open-source/files/3512419/C7A730925F25BA3DA70B0F7A21CD2B08EEE27.pdf)

[F2F3FB531C7079234E3647E962C32ECA12675F.pdf](https://github.com/jimmejardine/qiqqa-open-source/files/3512420/F2F3FB531C7079234E3647E962C32ECA12675F.pdf)

[46AA33B5235AB3E41D77B4B0BAF3CA74890901C.pdf](https://github.com/jimmejardine/qiqqa-open-source/files/3512421/46AA33B5235AB3E41D77B4B0BAF3CA74890901C.pdf)
